spring:
  application:
    name: UserService
  data:
    mongodb:
          uri: mongodb://localhost:27017/userdb
          database: userdb
  profiles:
    active: dev
server:
  port: 8082

build:
  id:9090

# Database Configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/user?options=-c%20timezone=UTC
#spring.datasource.username=vineet
#spring.datasource.password=8287685215
#
## JPA / Hibernate Settings
#spring.jpa.database=postgresql
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
